OK = 1
ERROR = 2
INITIALIZATION = 3
STOP = 4
AUTO = 5
MANUAL = 6
EMERGENCY_STOP = 7
SOFTWARE_STOP = 8

IGNITION = 9
NORMAL_OPERATION = 10
END_OF_FUEL = 11
FUEL_LOADING = 12

FUEL_LOADING_PRELOADING = 13
FUEL_LOADING_WAITING_FOR_FUEL = 14
FUEL_LOADING_WAITING_FOR_DOORS = 15
FUEL_LOADING_BOTTOM_TABLE = 16
FUEL_LOADING_TOP_TABLE = 17
FUEL_LOADING_BOTTOM_TABLE_BACK = 18
FUEL_LOADING_TOP_TABLE_BACK = 19
FUEL_LOADING_CLOSE_DOORS = 20